[profile.default]
src      = "src"
out      = "out"
libs     = ["lib"]
solc     = "0.8.24"
remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "forge-std/=lib/openzeppelin-contracts/lib/forge-std/src/",
]
optimizer        = true
optimizer_runs   = 200
via_ir           = true

[profile.default.rpc_endpoints]
monad_testnet = "https://testnet-rpc.monad.xyz"
monad_mainnet = "https://rpc.monad.xyz"

[profile.default.etherscan]
monad_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://testnet.monadexplorer.com/api" }
monad_mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://monadexplorer.com/api" }

[fmt]
line_length = 120
tab_width   = 4
bracket_spacing = true
